### ISSUE TITLE
Tp5 smarty 内置函数不起作用

### ISSUE THREAD

**Issue by symjie** [zoujingli/think-smarty#3]
Tp5 smarty 内置函数不起作用，{$smarty.request.name} 不能获取到对应的值，因为url为:http://www.xxx.com/Index/index/index/name/zhangsan。
在TP5中，针对上述的URL，只能通过Request::instance()->param('name')来获取值。
而{$smarty.request.name} 编译为$_GET['name'],所以无法获取值。楼主怎么解决

**Comment by ajiho** [comment]
> Tp5 smarty 内置函数不起作用，{$smarty.request.name} 不能获取到对应的值，因为url为:[http://www.xxx.com/Index/index/index/name/zhangsan。](http://www.xxx.com/Index/index/index/name/zhangsan%E3%80%82) 在TP5中，针对上述的URL，只能通过Request::instance()->param('name')来获取值。 而{$smarty.request.name} 编译为$_GET['name'],所以无法获取值。楼主怎么解决

兄弟你这个地址是个黄色网站啊
