### ISSUE TITLE
关于ForceCompile的设置，导致无法正确缓存的问题

### ISSUE THREAD

**Issue by doscriptsite** [zoujingli/think-smarty#4]
https://github.com/zoujingli/think-smarty/blob/442fe54cbf709c341dc71c3b3c5ffede31be224e/src/Smarty.php#L49

**此处ForceCompile的值不应该与Caching相同，会导致开启缓存情况下重新缓存。**
详见Smarty文档：[$force_compile](https://www.smarty.net/docs/zh_CN/variable.force.compile.tpl)

这么久以来，一直都没用过缓存...

**Comment by zoujingli** [comment]
debug模式时强制重写
